import { CommonCodeGroup, CommonCodeItem } from '../../modules/common-codes/common-code.entity';

/**
 * 시스템 공통코드 시드 — 설계/페이즈_화면/시스템관리자_화면_v1.0.HTML 의
 * COMMON_CODE_CATALOG 기준 (그룹 67개 · 코드 395건).
 * 재생성: extract-codes.js
 */
export const CODE_GROUP_SEED: Partial<CommonCodeGroup>[] = [
  { groupCode: 'USER_GROUP', groupName: '사용자 그룹', nameEn: 'User Group', domain: 'AUTH', policy: 'SYSTEM_LOCKED', description: '인증 토큰, 메뉴 채널, 권한 평가 (출처: 시스템관리자 §4.12)' },
  { groupCode: 'OPERATOR_ROLE', groupName: '운영자 Role', nameEn: 'Operator Role', domain: 'AUTH', policy: 'ADMIN_MANAGED', description: '운영 콘솔 Role, 업무 배정 (출처: 시스템관리자 §4.12, bk §4.5)' },
  { groupCode: 'ACCOUNT_STATUS', groupName: '계정 상태', nameEn: 'Account Status', domain: 'AUTH', policy: 'SYSTEM_LOCKED', description: '로그인, 계정관리, 보안 이벤트 (출처: bk §12.2, §13.4, 시스템관리자 §4.12)' },
  { groupCode: 'AUTH_FACTOR_TYPE', groupName: '인증 수단', nameEn: 'Authentication Factor Type', domain: 'AUTH', policy: 'SYSTEM_LOCKED', description: 'MFA, SSO, Step-up (출처: bk §3)' },
  { groupCode: 'TENANT_STATUS', groupName: '테넌트 상태', nameEn: 'Tenant Status', domain: 'TENANT', policy: 'SYSTEM_LOCKED', description: '이용회사 상태, 구독·업무 차단 (출처: bk §12.2, §13.4)' },
  { groupCode: 'TENANT_TIER', groupName: '테넌트 티어', nameEn: 'Tenant Tier', domain: 'TENANT', policy: 'ADMIN_MANAGED', description: '멀티테넌시 격리, 백업, 쿼터 (출처: bk §2, §12.2)' },
  { groupCode: 'SUBSCRIPTION_STATUS', groupName: '구독 상태', nameEn: 'Subscription Status', domain: 'BILLING', policy: 'ADMIN_MANAGED', description: '구독·요금, 기능 제한 (출처: bk §12.2, §13.4, 운영자 §11.2)' },
  { groupCode: 'ADMIN_ACCESS_MODE', groupName: '관리자 접근모드', nameEn: 'Admin Access Mode', domain: 'ACCESS', policy: 'SYSTEM_LOCKED', description: '운영자 접근 세션, 배너, 감사로그 (출처: bk §5, §12.2, 시스템관리자 §4.12)' },
  { groupCode: 'BOOKKEEPING_MODE', groupName: '기장 모드', nameEn: 'Bookkeeping Mode', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '회계·세무 업무 수행 주체 (출처: bk §21, 운영자 §11.2)' },
  { groupCode: 'PRIMARY_BOOKKEEPER', groupName: '주기장', nameEn: 'Primary Bookkeeper', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '마감·결산·신고 권한 귀속 (출처: 시스템관리자 §4.12)' },
  { groupCode: 'MENU_TYPE', groupName: '메뉴 유형', nameEn: 'Menu Type', domain: 'MENU', policy: 'SYSTEM_LOCKED', description: '메뉴 마스터, 권한 평가 (출처: bk §4.3, 시스템관리자 §4.12)' },
  { groupCode: 'ACTION_TYPE', groupName: '행위 유형', nameEn: 'Action Type', domain: 'MENU', policy: 'SYSTEM_LOCKED', description: '버튼 권한, API scope (출처: 시스템관리자 §4.12)' },
  { groupCode: 'GUARDRAIL_TYPE', groupName: '가드레일 유형', nameEn: 'Guardrail Type', domain: 'PERMISSION', policy: 'SYSTEM_LOCKED', description: '권한·위임 정책 (출처: bk §4.3, 시스템관리자 §4.12)' },
  { groupCode: 'STANDARD_STATUS', groupName: '표준 버전 상태', nameEn: 'Standard Version Status', domain: 'STANDARD', policy: 'SYSTEM_LOCKED', description: '표준 카탈로그 버전 (출처: bk §12.2, 운영자 §11.2)' },
  { groupCode: 'STANDARD_DISTRIBUTION_MODE', groupName: '표준 배포 모드', nameEn: 'Standard Distribution Mode', domain: 'STANDARD', policy: 'SYSTEM_LOCKED', description: '표준 배포 정책 (출처: bk §6, §12.2)' },
  { groupCode: 'JOB_STATUS', groupName: '배치 상태', nameEn: 'Job Status', domain: 'BATCH', policy: 'SYSTEM_LOCKED', description: '운영 배치, 큐, DLQ (출처: bk §14.5, 시스템관리자 §4.12)' },
  { groupCode: 'TIER_MIGRATION_STATUS', groupName: '티어 전환 상태', nameEn: 'Tier Migration Status', domain: 'TENANT', policy: 'ADMIN_MANAGED', description: '테넌트 티어 전환 작업 (출처: bk §12.2, 시스템관리자 §4.12)' },
  { groupCode: 'SECURITY_INCIDENT_STATUS', groupName: '보안 인시던트 상태', nameEn: 'Security Incident Status', domain: 'SECURITY', policy: 'SYSTEM_LOCKED', description: '보안 이벤트, IR (출처: bk §12.2, 시스템관리자 §4.12)' },
  { groupCode: 'SENSITIVITY_CLASS', groupName: '민감정보 등급', nameEn: 'Sensitivity Class', domain: 'SECURITY', policy: 'SYSTEM_LOCKED', description: '마스킹, 녹화, DLP (출처: 시스템관리자 §4.12)' },
  { groupCode: 'NOTIFICATION_CHANNEL', groupName: '알림 채널', nameEn: 'Notification Channel', domain: 'NOTIFICATION', policy: 'ADMIN_MANAGED', description: '알림 발송 (출처: 시스템관리자 §4.12)' },
  { groupCode: 'ERROR_CODE', groupName: '오류 코드', nameEn: 'Error Code', domain: 'ERROR', policy: 'ADMIN_MANAGED', description: 'API 오류, UI 복구 가이드 (출처: bk §26.4, 개발설계 API/예외 표)' },
  { groupCode: 'AUDIT_EVENT_TYPE', groupName: '감사 이벤트', nameEn: 'Audit Event Type', domain: 'AUDIT', policy: 'SYSTEM_LOCKED', description: '감사로그, 보안 이벤트 (출처: 시스템관리자 §4.12)' },
  { groupCode: 'FEATURE_FLAG_TYPE', groupName: '기능 플래그 유형', nameEn: 'Feature Flag Type', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '기능 플래그, 배포 게이트 (출처: 시스템관리자 §4.12)' },
  { groupCode: 'RETENTION_CLASS', groupName: '파일 보존 등급', nameEn: 'Retention Class', domain: 'RETENTION', policy: 'ADMIN_MANAGED', description: '데이터 티어링, 파기 (출처: 시스템관리자 §4.12)' },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', groupName: '기장 모드 전환 상태', nameEn: 'Bookkeeping Switch Status', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '기장 모드 변경 워크플로 (출처: bk §12.2, 운영자 §11.2)' },
  { groupCode: 'TENANT_ACK_STATUS', groupName: '이용회사 확인 상태', nameEn: 'Tenant Acknowledgement Status', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '마감·신고·보고 확인 (출처: bk §12.2, 운영자 §11.2)' },
  { groupCode: 'BREAK_GLASS_STATUS', groupName: '긴급대행 상태', nameEn: 'Break-glass Status', domain: 'SECURITY', policy: 'SYSTEM_LOCKED', description: '긴급 접근 승인·검토 (출처: bk §12.2, 시스템관리자 §6.3)' },
  { groupCode: 'DIMENSION_ASSIGNMENT_JOB_STATUS', groupName: '차원 배정잡 상태', nameEn: 'Dimension Assignment Job Status', domain: 'BATCH', policy: 'ADMIN_MANAGED', description: '차원 일괄배정 배치 (출처: bk §12.2)' },
  { groupCode: 'CONVERSION_BATCH_STATUS', groupName: '변환 배치 상태', nameEn: 'Conversion Batch Status', domain: 'BATCH', policy: 'ADMIN_MANAGED', description: '회계기준/외부자료 변환 배치 (출처: bk §12.2, §13.4, §14.5)' },
  { groupCode: 'COLLECTION_TASK_STATUS', groupName: '수집 태스크 상태', nameEn: 'Collection Task Status', domain: 'BATCH', policy: 'SYSTEM_LOCKED', description: '외부수집, 스크래핑, 큐 (출처: bk §12.2, 시스템관리자 §6.3)' },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', groupName: '공시자료 상태', nameEn: 'Disclosure Document Status', domain: 'REPORT', policy: 'ADMIN_MANAGED', description: '공시자료·XBRL 생성/제출 (출처: bk §12.2, §13.4)' },
  { groupCode: 'ANOMALY_ALERT_STATUS', groupName: '이상 알림 상태', nameEn: 'Anomaly Alert Status', domain: 'AUDIT', policy: 'ADMIN_MANAGED', description: '이상거래 알림 처리 (출처: bk §12.2, §13.4)' },
  { groupCode: 'ANOMALY_MODEL_STATUS', groupName: '이상 모델 상태', nameEn: 'Anomaly Model Status', domain: 'AUDIT', policy: 'ADMIN_MANAGED', description: '이상탐지 모델 생명주기 (출처: bk §12.2)' },
  { groupCode: 'CHATBOT_SESSION_STATUS', groupName: '챗봇 세션 상태', nameEn: 'Chatbot Session Status', domain: 'AI', policy: 'ADMIN_MANAGED', description: 'AI 조회 챗봇 세션 (출처: bk §12.2, §13.4)' },
  { groupCode: 'FISCAL_PERIOD_STATUS', groupName: '회계기간 상태', nameEn: 'Fiscal Period Status', domain: 'ACCOUNTING', policy: 'SYSTEM_LOCKED', description: '회계기간, 마감 잠금 (출처: bk §12.2, 페이즈02/05)' },
  { groupCode: 'JOURNAL_ENTRY_CODE', groupName: '전표 분개구분', nameEn: 'Journal Entry Code', domain: 'JOURNAL', policy: 'SYSTEM_LOCKED', description: '전표 라인 차대·결산·세무 조정 (출처: bk §11.1, §12.2, 페이즈03/05)' },
  { groupCode: 'NOTIFICATION_DELIVERY_STATUS', groupName: '알림 발송 상태', nameEn: 'Notification Delivery Status', domain: 'NOTIFICATION', policy: 'SYSTEM_LOCKED', description: '알림 발송·읽음 처리 (출처: bk §12.2)' },
  { groupCode: 'EVIDENCE_STATUS', groupName: '증빙 상태', nameEn: 'Evidence Status', domain: 'EVIDENCE', policy: 'ADMIN_MANAGED', description: '증빙 수집·검증·매칭 (출처: bk §12.2, 페이즈06/07)' },
  { groupCode: 'REPORT_PACKAGE_STATUS', groupName: '보고패키지 상태', nameEn: 'Report Package Status', domain: 'REPORT', policy: 'ADMIN_MANAGED', description: '월별 보고패키지 조립·전달 (출처: bk §12.2, 운영자 §11.2)' },
  { groupCode: 'TIE_OUT_STATUS', groupName: '계정 명세 Tie-out 상태', nameEn: 'Tie-out Status', domain: 'REPORT', policy: 'ADMIN_MANAGED', description: '계정별 명세 대사 결과 (출처: bk §12.2)' },
  { groupCode: 'OPEN_ITEM_STATUS', groupName: '미결항목 상태', nameEn: 'Open Item Status', domain: 'ACCOUNTING', policy: 'ADMIN_MANAGED', description: '미결항목 회신·해소 (출처: bk §12.2, 운영자 §11.2)' },
  { groupCode: 'GROUP_REPORT_EXPORT_STATUS', groupName: '그룹보고 Export 상태', nameEn: 'Group Report Export Status', domain: 'REPORT', policy: 'ADMIN_MANAGED', description: '그룹 보고 Export (출처: bk §12.2)' },
  { groupCode: 'COST_CALCULATION_STATUS', groupName: '제조원가 계산 상태', nameEn: 'Cost Calculation Status', domain: 'COST', policy: 'ADMIN_MANAGED', description: '제조원가 계산·승인 (출처: bk §12.2, 페이즈05)' },
  { groupCode: 'NTS_TRANSMISSION_STATUS', groupName: '국세청 전송상태', nameEn: 'NTS Transmission Status', domain: 'VAT', policy: 'ADMIN_MANAGED', description: '국세청/홈택스 전송·대사 (출처: bk §11.4, §12.2, 페이즈07)' },
  { groupCode: 'JOURNAL_TYPE', groupName: '전표 유형', nameEn: 'Journal Type', domain: 'JOURNAL', policy: 'ADMIN_MANAGED', description: '화면 구분 컬럼, 입출금 자동 판별 (출처: bk §12.2, 페이즈03)' },
  { groupCode: 'JOURNAL_NUMBERING_STATUS', groupName: '전표번호 채번 상태', nameEn: 'Journal Numbering Status', domain: 'JOURNAL', policy: 'SYSTEM_LOCKED', description: '일자별 전표번호 채번·결번 (출처: bk §12.2, 페이즈10)' },
  { groupCode: 'BUSINESS_PARTNER_STATUS', groupName: '거래처 상태', nameEn: 'Business Partner Status', domain: 'MASTERDATA', policy: 'ADMIN_MANAGED', description: '거래처 승인·휴폐업 통제 (출처: bk §12.2, 페이즈01/04)' },
  { groupCode: 'JOURNAL_STATUS', groupName: '전표 상태', nameEn: 'Journal Status', domain: 'JOURNAL', policy: 'SYSTEM_LOCKED', description: '전표 작성·승인·기표·취소 (출처: bk §13.4, §14.5)' },
  { groupCode: 'APPROVAL_STATUS', groupName: '결재 상태', nameEn: 'Approval Status', domain: 'APPROVAL', policy: 'SYSTEM_LOCKED', description: '전자결재·승인 워크플로 (출처: bk §13.4, §14.5)' },
  { groupCode: 'SERVICE_CONTRACT_STATUS', groupName: '서비스계약 상태', nameEn: 'Service Contract Status', domain: 'CONTRACT', policy: 'ADMIN_MANAGED', description: '서비스 계약 생명주기 (출처: bk §14.5)' },
  { groupCode: 'ASSIGNMENT_STATUS', groupName: '담당배정 상태', nameEn: 'Assignment Status', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '담당자 배정·이관 (출처: bk §14.5)' },
  { groupCode: 'CLIENT_TASK_STATUS', groupName: '고객업무 상태', nameEn: 'Client Task Status', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '고객 자료요청·검토·완료 (출처: bk §14.5)' },
  { groupCode: 'TAX_INVOICE_STATUS', groupName: '세금계산서 상태', nameEn: 'Tax Invoice Status', domain: 'VAT', policy: 'ADMIN_MANAGED', description: '세금계산서 전송·재시도 (출처: bk §14.5)' },
  { groupCode: 'FILING_FILE_STATUS', groupName: '신고파일 상태', nameEn: 'Filing File Status', domain: 'TAX', policy: 'ADMIN_MANAGED', description: '신고파일 생성·제출 (출처: bk §14.5, 페이즈06)' },
  { groupCode: 'ASSET_STATUS', groupName: '자산 상태', nameEn: 'Asset Status', domain: 'ASSET', policy: 'ADMIN_MANAGED', description: '고정자산 생명주기 (출처: bk §14.5, 페이즈08)' },
  { groupCode: 'VAT_RETURN_TYPE', groupName: '부가세신고유형', nameEn: 'VAT Return Type', domain: 'VAT', policy: 'ADMIN_MANAGED', description: '부가세 신고 구분 (출처: bk §14.5, 페이즈06)' },
  { groupCode: 'BOOKKEEPING_SCOPE_TYPE', groupName: '기장 분담 기준', nameEn: 'Bookkeeping Scope Type', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: 'HYBRID 업무 분담 규칙 (출처: 운영자 §9.5, bk §21.6)' },
  { groupCode: 'STANDARD_CATALOG_CODE', groupName: '표준 카탈로그 코드', nameEn: 'Standard Catalog Code', domain: 'STANDARD', policy: 'STANDARD_MANAGED', description: '공통 표준 카탈로그 종류 (출처: bk §6.1, 페이즈01)' },
  { groupCode: 'DIMENSION_TYPE', groupName: '관리차원 유형', nameEn: 'Dimension Type', domain: 'MASTERDATA', policy: 'STANDARD_MANAGED', description: '전표 라인·보고 차원 (출처: bk §9, 페이즈01)' },
  { groupCode: 'JOURNAL_APPROVAL_MODE', groupName: '전표 결재 모드', nameEn: 'Journal Approval Mode', domain: 'JOURNAL', policy: 'ADMIN_MANAGED', description: '회사별 전표 결재 옵션 (출처: bk §11.1)' },
  { groupCode: 'CASH_FLOW_ACTIVITY', groupName: '현금흐름 활동구분', nameEn: 'Cash Flow Activity', domain: 'REPORT', policy: 'STANDARD_MANAGED', description: '현금흐름표 활동 구분 (출처: bk §11.3.1, 페이즈05)' },
  { groupCode: 'DISCLOSURE_REPORT_TYPE', groupName: '공시 보고서 유형', nameEn: 'Disclosure Report Type', domain: 'REPORT', policy: 'STANDARD_MANAGED', description: '공시자료·XBRL 산출 유형 (출처: bk §11.3.2)' },
  { groupCode: 'ACCOUNTING_STANDARD', groupName: '회계기준', nameEn: 'Accounting Standard', domain: 'ACCOUNTING', policy: 'STANDARD_MANAGED', description: '다중 회계기준·변환 (출처: bk §11.6)' },
  { groupCode: 'AUX_LEDGER_TYPE', groupName: '보조원장 유형', nameEn: 'Auxiliary Ledger Type', domain: 'LEDGER', policy: 'STANDARD_MANAGED', description: '전표 라인 보조부 연결 (출처: bk §12.1)' },
  { groupCode: 'TENANT_INPUT_POLICY', groupName: '이용회사 입력 정책', nameEn: 'Tenant Input Policy', domain: 'OPERATION', policy: 'ADMIN_MANAGED', description: '기장대행 회사의 이용회사 입력 허용범위 (출처: bk §11.1, 페이즈09)' },
  { groupCode: 'BILL_RECEIVABLE_STATUS', groupName: '받을어음 상태', nameEn: 'Bill Receivable Status', domain: 'TREASURY', policy: 'ADMIN_MANAGED', description: '받을어음 보관·할인·배서·만기 (출처: 페이즈09 §자금·어음)' },
  { groupCode: 'BILL_PAPER_STATUS', groupName: '어음 용지 상태', nameEn: 'Bill Paper Status', domain: 'TREASURY', policy: 'ADMIN_MANAGED', description: '어음 용지 발행·결제·폐기 (출처: 페이즈09 §자금·어음)' },
];

export const CODE_ITEM_SEED: Partial<CommonCodeItem>[] = [
  { groupCode: 'USER_GROUP', code: 'OPERATOR', name: '관리회사 운영자', nameEn: 'Operator', sortOrder: 1, isActive: true },
  { groupCode: 'USER_GROUP', code: 'TENANT', name: '이용회사 사용자', nameEn: 'Tenant User', sortOrder: 2, isActive: true },
  { groupCode: 'OPERATOR_ROLE', code: 'BK_MANAGER', name: '기장 책임', nameEn: 'Bookkeeping Manager', sortOrder: 1, isActive: true },
  { groupCode: 'OPERATOR_ROLE', code: 'BK_PREPARER', name: '기장 담당', nameEn: 'Bookkeeping Preparer', sortOrder: 2, isActive: true },
  { groupCode: 'OPERATOR_ROLE', code: 'BK_REVIEWER', name: '기장 검토', nameEn: 'Bookkeeping Reviewer', sortOrder: 3, isActive: true },
  { groupCode: 'OPERATOR_ROLE', code: 'SEC_ADMIN', name: '시스템관리자', nameEn: 'Security/System Admin', sortOrder: 4, isActive: true },
  { groupCode: 'OPERATOR_ROLE', code: 'AUDITOR', name: '감사자', nameEn: 'Auditor', sortOrder: 5, isActive: true },
  { groupCode: 'OPERATOR_ROLE', code: 'BILLING', name: '청구 담당', nameEn: 'Billing', sortOrder: 6, isActive: true },
  { groupCode: 'ACCOUNT_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 1, isActive: true },
  { groupCode: 'ACCOUNT_STATUS', code: 'LOCKED', name: '잠금', nameEn: 'Locked', sortOrder: 2, isActive: true },
  { groupCode: 'ACCOUNT_STATUS', code: 'PASSWORD_EXPIRED', name: '비밀번호 만료', nameEn: 'Password Expired', sortOrder: 3, isActive: true },
  { groupCode: 'ACCOUNT_STATUS', code: 'SUSPENDED', name: '정지', nameEn: 'Suspended', sortOrder: 4, isActive: true },
  { groupCode: 'ACCOUNT_STATUS', code: 'DORMANT', name: '휴면', nameEn: 'Dormant', sortOrder: 5, isActive: true },
  { groupCode: 'ACCOUNT_STATUS', code: 'DISABLED', name: '비활성', nameEn: 'Disabled', sortOrder: 6, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'PASSWORD', name: '비밀번호', nameEn: 'Password', sortOrder: 1, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'TOTP', name: 'OTP 앱', nameEn: 'TOTP', sortOrder: 2, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'SMS_OTP', name: 'SMS OTP', nameEn: 'SMS OTP', sortOrder: 3, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'EMAIL_OTP', name: '이메일 OTP', nameEn: 'Email OTP', sortOrder: 4, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'WEBAUTHN', name: '패스키/WebAuthn', nameEn: 'WebAuthn', sortOrder: 5, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'BACKUP_CODE', name: '백업 코드', nameEn: 'Backup Code', sortOrder: 6, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'SAML', name: 'SAML SSO', nameEn: 'SAML', sortOrder: 7, isActive: true },
  { groupCode: 'AUTH_FACTOR_TYPE', code: 'OIDC', name: 'OIDC SSO', nameEn: 'OIDC', sortOrder: 8, isActive: true },
  { groupCode: 'TENANT_STATUS', code: 'PENDING', name: '가입대기', nameEn: 'Pending', sortOrder: 1, isActive: true },
  { groupCode: 'TENANT_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 2, isActive: true },
  { groupCode: 'TENANT_STATUS', code: 'SUSPENDED', name: '정지', nameEn: 'Suspended', sortOrder: 3, isActive: true },
  { groupCode: 'TENANT_STATUS', code: 'DORMANT', name: '휴면', nameEn: 'Dormant', sortOrder: 4, isActive: true },
  { groupCode: 'TENANT_STATUS', code: 'TERMINATED', name: '종료', nameEn: 'Terminated', sortOrder: 5, isActive: true },
  { groupCode: 'TENANT_TIER', code: 'SHARED', name: '공유', nameEn: 'Shared', sortOrder: 1, isActive: true },
  { groupCode: 'TENANT_TIER', code: 'SCHEMA', name: '스키마 분리', nameEn: 'Schema', sortOrder: 2, isActive: true },
  { groupCode: 'TENANT_TIER', code: 'DEDICATED', name: '전용', nameEn: 'Dedicated', sortOrder: 3, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'TRIAL', name: '체험', nameEn: 'Trial', sortOrder: 1, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'ACTIVE', name: '정상', nameEn: 'Active', sortOrder: 2, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'PAST_DUE', name: '연체', nameEn: 'Past Due', sortOrder: 3, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'SUSPENDED', name: '정지', nameEn: 'Suspended', sortOrder: 4, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'GRACE', name: '유예', nameEn: 'Grace', sortOrder: 5, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'TERMINATED', name: '해지', nameEn: 'Terminated', sortOrder: 6, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'REACTIVATED', name: '재활성', nameEn: 'Reactivated', sortOrder: 7, isActive: true },
  { groupCode: 'SUBSCRIPTION_STATUS', code: 'CANCELED', name: '취소', nameEn: 'Canceled', sortOrder: 8, isActive: true },
  { groupCode: 'ADMIN_ACCESS_MODE', code: 'VIEW', name: '조회 지원', nameEn: 'View', sortOrder: 1, isActive: true },
  { groupCode: 'ADMIN_ACCESS_MODE', code: 'SUPPORT_SESSION', name: '지원 세션', nameEn: 'Support Session', sortOrder: 2, isActive: true },
  { groupCode: 'ADMIN_ACCESS_MODE', code: 'BOOKKEEPING', name: '기장 수행', nameEn: 'Bookkeeping', sortOrder: 3, isActive: true },
  { groupCode: 'ADMIN_ACCESS_MODE', code: 'BREAK_GLASS', name: '긴급대행', nameEn: 'Break Glass', sortOrder: 4, isActive: true },
  { groupCode: 'BOOKKEEPING_MODE', code: 'OPERATOR_LED', name: '관리회사 주도', nameEn: 'Operator Led', sortOrder: 1, isActive: true },
  { groupCode: 'BOOKKEEPING_MODE', code: 'TENANT_LED', name: '이용회사 주도', nameEn: 'Tenant Led', sortOrder: 2, isActive: true },
  { groupCode: 'BOOKKEEPING_MODE', code: 'HYBRID', name: '혼합', nameEn: 'Hybrid', sortOrder: 3, isActive: true },
  { groupCode: 'PRIMARY_BOOKKEEPER', code: 'OPERATOR', name: '관리회사', nameEn: 'Operator', sortOrder: 1, isActive: true },
  { groupCode: 'PRIMARY_BOOKKEEPER', code: 'TENANT', name: '이용회사', nameEn: 'Tenant', sortOrder: 2, isActive: true },
  { groupCode: 'MENU_TYPE', code: 'GROUP', name: '그룹', nameEn: 'Group', sortOrder: 1, isActive: true },
  { groupCode: 'MENU_TYPE', code: 'MENU', name: '진입 메뉴', nameEn: 'Menu', sortOrder: 2, isActive: true },
  { groupCode: 'MENU_TYPE', code: 'TAB', name: '탭', nameEn: 'Tab', sortOrder: 3, isActive: true },
  { groupCode: 'MENU_TYPE', code: 'ACTION', name: '행위', nameEn: 'Action', sortOrder: 4, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'READ', name: '조회', nameEn: 'Read', sortOrder: 1, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'CREATE', name: '등록', nameEn: 'Create', sortOrder: 2, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'UPDATE', name: '수정', nameEn: 'Update', sortOrder: 3, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'DELETE', name: '삭제', nameEn: 'Delete', sortOrder: 4, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'APPROVE', name: '승인', nameEn: 'Approve', sortOrder: 5, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'REJECT', name: '반려', nameEn: 'Reject', sortOrder: 6, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'CLOSE', name: '마감', nameEn: 'Close', sortOrder: 7, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'REOPEN', name: '마감해제', nameEn: 'Reopen', sortOrder: 8, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'SUBMIT', name: '전송', nameEn: 'Submit', sortOrder: 9, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'EXPORT', name: '출력', nameEn: 'Export', sortOrder: 10, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'PUBLISH', name: '발행', nameEn: 'Publish', sortOrder: 11, isActive: true },
  { groupCode: 'ACTION_TYPE', code: 'ROLLBACK', name: '롤백', nameEn: 'Rollback', sortOrder: 12, isActive: true },
  { groupCode: 'GUARDRAIL_TYPE', code: 'FORBID', name: '금지', nameEn: 'Forbid', sortOrder: 1, isActive: true },
  { groupCode: 'GUARDRAIL_TYPE', code: 'REQUIRE_SOD', name: '직무분리 필요', nameEn: 'Require SOD', sortOrder: 2, isActive: true },
  { groupCode: 'GUARDRAIL_TYPE', code: 'REQUIRE_STEPUP', name: '재인증 필요', nameEn: 'Require Step-up', sortOrder: 3, isActive: true },
  { groupCode: 'GUARDRAIL_TYPE', code: 'REQUIRE_APPROVAL', name: '승인 필요', nameEn: 'Require Approval', sortOrder: 4, isActive: true },
  { groupCode: 'STANDARD_STATUS', code: 'DRAFT', name: '작성중', nameEn: 'Draft', sortOrder: 1, isActive: true },
  { groupCode: 'STANDARD_STATUS', code: 'PUBLISHED', name: '발행', nameEn: 'Published', sortOrder: 2, isActive: true },
  { groupCode: 'STANDARD_STATUS', code: 'DEPRECATED', name: '폐기예정', nameEn: 'Deprecated', sortOrder: 3, isActive: true },
  { groupCode: 'STANDARD_STATUS', code: 'RETIRED', name: '퇴역', nameEn: 'Retired', sortOrder: 4, isActive: true },
  { groupCode: 'STANDARD_DISTRIBUTION_MODE', code: 'MANDATORY', name: '강제', nameEn: 'Mandatory', sortOrder: 1, isActive: true },
  { groupCode: 'STANDARD_DISTRIBUTION_MODE', code: 'RECOMMENDED', name: '권고', nameEn: 'Recommended', sortOrder: 2, isActive: true },
  { groupCode: 'STANDARD_DISTRIBUTION_MODE', code: 'OPTIONAL', name: '선택', nameEn: 'Optional', sortOrder: 3, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'READY', name: '준비', nameEn: 'Ready', sortOrder: 1, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'QUEUED', name: '대기열', nameEn: 'Queued', sortOrder: 2, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'RUNNING', name: '실행중', nameEn: 'Running', sortOrder: 3, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'SUCCESS', name: '성공', nameEn: 'Success', sortOrder: 4, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'RETRY', name: '재시도', nameEn: 'Retry', sortOrder: 5, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 6, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'DEAD_LETTER', name: 'DLQ', nameEn: 'Dead Letter', sortOrder: 7, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'PARTIAL_SUCCESS', name: '부분성공', nameEn: 'Partial Success', sortOrder: 8, isActive: true },
  { groupCode: 'JOB_STATUS', code: 'CANCELLED', name: '취소', nameEn: 'Cancelled', sortOrder: 9, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'SCHEDULED', name: '예약', nameEn: 'Scheduled', sortOrder: 1, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'PROVISIONING', name: '프로비저닝', nameEn: 'Provisioning', sortOrder: 2, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'SNAPSHOTTING', name: '스냅샷', nameEn: 'Snapshotting', sortOrder: 3, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'CDC_SYNC', name: 'CDC 동기화', nameEn: 'CDC Sync', sortOrder: 4, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'VALIDATING', name: '검증', nameEn: 'Validating', sortOrder: 5, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'CUTOVER', name: '전환', nameEn: 'Cutover', sortOrder: 6, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'COMPLETED', name: '완료', nameEn: 'Completed', sortOrder: 7, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'ROLLED_BACK', name: '롤백', nameEn: 'Rolled Back', sortOrder: 8, isActive: true },
  { groupCode: 'TIER_MIGRATION_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 9, isActive: true },
  { groupCode: 'SECURITY_INCIDENT_STATUS', code: 'DETECTED', name: '탐지', nameEn: 'Detected', sortOrder: 1, isActive: true },
  { groupCode: 'SECURITY_INCIDENT_STATUS', code: 'CONTAINED', name: '격리', nameEn: 'Contained', sortOrder: 2, isActive: true },
  { groupCode: 'SECURITY_INCIDENT_STATUS', code: 'ANALYZING', name: '분석중', nameEn: 'Analyzing', sortOrder: 3, isActive: true },
  { groupCode: 'SECURITY_INCIDENT_STATUS', code: 'RECOVERED', name: '복구', nameEn: 'Recovered', sortOrder: 4, isActive: true },
  { groupCode: 'SECURITY_INCIDENT_STATUS', code: 'NOTIFIED', name: '통지', nameEn: 'Notified', sortOrder: 5, isActive: true },
  { groupCode: 'SECURITY_INCIDENT_STATUS', code: 'CLOSED', name: '종결', nameEn: 'Closed', sortOrder: 6, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'PUBLIC', name: '공개', nameEn: 'Public', sortOrder: 1, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'INTERNAL', name: '내부', nameEn: 'Internal', sortOrder: 2, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'PII', name: '개인정보', nameEn: 'PII', sortOrder: 3, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'FINANCIAL', name: '금융정보', nameEn: 'Financial', sortOrder: 4, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'PAYROLL', name: '급여', nameEn: 'Payroll', sortOrder: 5, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'SECRET', name: '비밀', nameEn: 'Secret', sortOrder: 6, isActive: true },
  { groupCode: 'SENSITIVITY_CLASS', code: 'PASSWORD', name: '비밀번호', nameEn: 'Password', sortOrder: 7, isActive: true },
  { groupCode: 'NOTIFICATION_CHANNEL', code: 'IN_APP', name: '인앱', nameEn: 'In App', sortOrder: 1, isActive: true },
  { groupCode: 'NOTIFICATION_CHANNEL', code: 'EMAIL', name: '이메일', nameEn: 'Email', sortOrder: 2, isActive: true },
  { groupCode: 'NOTIFICATION_CHANNEL', code: 'SMS', name: '문자', nameEn: 'SMS', sortOrder: 3, isActive: true },
  { groupCode: 'NOTIFICATION_CHANNEL', code: 'KAKAO', name: '카카오', nameEn: 'Kakao', sortOrder: 4, isActive: true },
  { groupCode: 'NOTIFICATION_CHANNEL', code: 'WEBHOOK', name: '웹훅', nameEn: 'Webhook', sortOrder: 5, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'STEP_UP_REQUIRED', name: '재인증 필요', nameEn: 'Step-up Required', sortOrder: 1, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'CONSOLE_IP_BLOCKED', name: '콘솔 IP 차단', nameEn: 'Console IP Blocked', sortOrder: 2, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'ACCESS_SESSION_REQUIRED', name: '접근 세션 필요', nameEn: 'Access Session Required', sortOrder: 3, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'BULK_ACTION_THRESHOLD', name: '대량행위 임계 초과', nameEn: 'Bulk Action Threshold', sortOrder: 4, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'FORBIDDEN_SCOPE', name: '권한 범위 없음', nameEn: 'Forbidden Scope', sortOrder: 5, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'VALIDATION_FAILED', name: '검증 실패', nameEn: 'Validation Failed', sortOrder: 6, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'CLOSING_LOCKED', name: '마감 잠금', nameEn: 'Closing Locked', sortOrder: 7, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'PERIOD_LOCKED', name: '기간 잠금', nameEn: 'Period Locked', sortOrder: 8, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'NOT_PRIMARY_BOOKKEEPER', name: '주기장 아님', nameEn: 'Not Primary Bookkeeper', sortOrder: 9, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'BOOKKEEPING_NOT_CONTRACTED', name: '기장 계약 없음', nameEn: 'Bookkeeping Not Contracted', sortOrder: 10, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'IDEMPOTENCY_CONFLICT', name: '멱등키 충돌', nameEn: 'Idempotency Conflict', sortOrder: 11, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'EXTERNAL_INTEGRATION_FAILED', name: '외부연계 실패', nameEn: 'External Integration Failed', sortOrder: 12, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'RATE_LIMITED', name: '요청 제한', nameEn: 'Rate Limited', sortOrder: 13, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'POSTED_IMMUTABLE', name: '기표 후 불변', nameEn: 'Posted Immutable', sortOrder: 14, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'NUMBERING_CONFLICT', name: '채번 충돌', nameEn: 'Numbering Conflict', sortOrder: 15, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'LOCK_NOT_ACQUIRED', name: '잠금 획득 실패', nameEn: 'Lock Not Acquired', sortOrder: 16, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'TENANT_ACCESS_DENIED', name: '테넌트 접근 거부', nameEn: 'Tenant Access Denied', sortOrder: 17, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'COMMON_CODE_GROUP_REQUIRED', name: '공통코드 마스터 필요', nameEn: 'Common Code Group Required', sortOrder: 18, isActive: true },
  { groupCode: 'ERROR_CODE', code: 'COMMON_CODE_GROUP_ITEM_MISMATCH', name: '마스터/세부 불일치', nameEn: 'Common Code Group Item Mismatch', sortOrder: 19, isActive: true },
  { groupCode: 'AUDIT_EVENT_TYPE', code: 'LOGIN', name: '로그인', nameEn: 'Login', sortOrder: 1, isActive: true },
  { groupCode: 'AUDIT_EVENT_TYPE', code: 'ACCESS_SESSION_START', name: '접근 세션 시작', nameEn: 'Access Session Start', sortOrder: 2, isActive: true },
  { groupCode: 'AUDIT_EVENT_TYPE', code: 'DATA_EXPORT', name: '자료 내보내기', nameEn: 'Data Export', sortOrder: 3, isActive: true },
  { groupCode: 'AUDIT_EVENT_TYPE', code: 'ROLE_CHANGED', name: 'Role 변경', nameEn: 'Role Changed', sortOrder: 4, isActive: true },
  { groupCode: 'AUDIT_EVENT_TYPE', code: 'KEY_ROTATED', name: '키 회전', nameEn: 'Key Rotated', sortOrder: 5, isActive: true },
  { groupCode: 'AUDIT_EVENT_TYPE', code: 'CODE_PUBLISHED', name: '코드 발행', nameEn: 'Code Published', sortOrder: 6, isActive: true },
  { groupCode: 'FEATURE_FLAG_TYPE', code: 'GLOBAL', name: '전역', nameEn: 'Global', sortOrder: 1, isActive: true },
  { groupCode: 'FEATURE_FLAG_TYPE', code: 'PLAN', name: '요금제', nameEn: 'Plan', sortOrder: 2, isActive: true },
  { groupCode: 'FEATURE_FLAG_TYPE', code: 'TENANT', name: '테넌트', nameEn: 'Tenant', sortOrder: 3, isActive: true },
  { groupCode: 'FEATURE_FLAG_TYPE', code: 'USER', name: '사용자', nameEn: 'User', sortOrder: 4, isActive: true },
  { groupCode: 'FEATURE_FLAG_TYPE', code: 'EXPERIMENT', name: '실험', nameEn: 'Experiment', sortOrder: 5, isActive: true },
  { groupCode: 'RETENTION_CLASS', code: 'HOT', name: '핫', nameEn: 'Hot', sortOrder: 1, isActive: true },
  { groupCode: 'RETENTION_CLASS', code: 'WARM', name: '웜', nameEn: 'Warm', sortOrder: 2, isActive: true },
  { groupCode: 'RETENTION_CLASS', code: 'COLD', name: '콜드', nameEn: 'Cold', sortOrder: 3, isActive: true },
  { groupCode: 'RETENTION_CLASS', code: 'WORM', name: '불변보관', nameEn: 'WORM', sortOrder: 4, isActive: true },
  { groupCode: 'RETENTION_CLASS', code: 'DESTROY_PENDING', name: '파기대기', nameEn: 'Destroy Pending', sortOrder: 5, isActive: true },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', code: 'REQUESTED', name: '요청', nameEn: 'Requested', sortOrder: 1, isActive: true },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', code: 'COUNTERPARTY_CONSENTED', name: '상대 동의', nameEn: 'Counterparty Consented', sortOrder: 2, isActive: true },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', code: 'SCHEDULED', name: '예약', nameEn: 'Scheduled', sortOrder: 3, isActive: true },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', code: 'SWITCHED', name: '전환완료', nameEn: 'Switched', sortOrder: 4, isActive: true },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 5, isActive: true },
  { groupCode: 'BOOKKEEPING_SWITCH_STATUS', code: 'CANCELLED', name: '취소', nameEn: 'Cancelled', sortOrder: 6, isActive: true },
  { groupCode: 'TENANT_ACK_STATUS', code: 'PENDING', name: '대기', nameEn: 'Pending', sortOrder: 1, isActive: true },
  { groupCode: 'TENANT_ACK_STATUS', code: 'CONFIRMED', name: '확인', nameEn: 'Confirmed', sortOrder: 2, isActive: true },
  { groupCode: 'TENANT_ACK_STATUS', code: 'OBJECTED', name: '이의제기', nameEn: 'Objected', sortOrder: 3, isActive: true },
  { groupCode: 'BREAK_GLASS_STATUS', code: 'REQUESTED', name: '요청', nameEn: 'Requested', sortOrder: 1, isActive: true },
  { groupCode: 'BREAK_GLASS_STATUS', code: 'APPROVED', name: '승인', nameEn: 'Approved', sortOrder: 2, isActive: true },
  { groupCode: 'BREAK_GLASS_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 3, isActive: true },
  { groupCode: 'BREAK_GLASS_STATUS', code: 'EXPIRED', name: '만료', nameEn: 'Expired', sortOrder: 4, isActive: true },
  { groupCode: 'BREAK_GLASS_STATUS', code: 'REVOKED', name: '회수', nameEn: 'Revoked', sortOrder: 5, isActive: true },
  { groupCode: 'BREAK_GLASS_STATUS', code: 'REVIEWED', name: '검토완료', nameEn: 'Reviewed', sortOrder: 6, isActive: true },
  { groupCode: 'DIMENSION_ASSIGNMENT_JOB_STATUS', code: 'READY', name: '준비', nameEn: 'Ready', sortOrder: 1, isActive: true },
  { groupCode: 'DIMENSION_ASSIGNMENT_JOB_STATUS', code: 'RUNNING', name: '실행중', nameEn: 'Running', sortOrder: 2, isActive: true },
  { groupCode: 'DIMENSION_ASSIGNMENT_JOB_STATUS', code: 'SUCCESS', name: '성공', nameEn: 'Success', sortOrder: 3, isActive: true },
  { groupCode: 'DIMENSION_ASSIGNMENT_JOB_STATUS', code: 'PARTIAL', name: '부분완료', nameEn: 'Partial', sortOrder: 4, isActive: true },
  { groupCode: 'DIMENSION_ASSIGNMENT_JOB_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 5, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'RECEIVED', name: '수신', nameEn: 'Received', sortOrder: 1, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'VALIDATED', name: '검증완료', nameEn: 'Validated', sortOrder: 2, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'MAPPED', name: '매핑완료', nameEn: 'Mapped', sortOrder: 3, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'CONVERTED', name: '변환완료', nameEn: 'Converted', sortOrder: 4, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'STAGED', name: '스테이징', nameEn: 'Staged', sortOrder: 5, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'REVIEWING', name: '검토중', nameEn: 'Reviewing', sortOrder: 6, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'POSTED', name: '기표', nameEn: 'Posted', sortOrder: 7, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 8, isActive: true },
  { groupCode: 'CONVERSION_BATCH_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 9, isActive: true },
  { groupCode: 'COLLECTION_TASK_STATUS', code: 'QUEUED', name: '대기열', nameEn: 'Queued', sortOrder: 1, isActive: true },
  { groupCode: 'COLLECTION_TASK_STATUS', code: 'RUNNING', name: '실행중', nameEn: 'Running', sortOrder: 2, isActive: true },
  { groupCode: 'COLLECTION_TASK_STATUS', code: 'SUCCESS', name: '성공', nameEn: 'Success', sortOrder: 3, isActive: true },
  { groupCode: 'COLLECTION_TASK_STATUS', code: 'RETRY', name: '재시도', nameEn: 'Retry', sortOrder: 4, isActive: true },
  { groupCode: 'COLLECTION_TASK_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 5, isActive: true },
  { groupCode: 'COLLECTION_TASK_STATUS', code: 'DEAD_LETTER', name: 'DLQ', nameEn: 'Dead Letter', sortOrder: 6, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'DRAFT', name: '작성중', nameEn: 'Draft', sortOrder: 1, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'GENERATED', name: '생성', nameEn: 'Generated', sortOrder: 2, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'VALIDATED', name: '검증', nameEn: 'Validated', sortOrder: 3, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'APPROVED', name: '승인', nameEn: 'Approved', sortOrder: 4, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'SUBMITTED', name: '제출', nameEn: 'Submitted', sortOrder: 5, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'ACCEPTED', name: '접수', nameEn: 'Accepted', sortOrder: 6, isActive: true },
  { groupCode: 'DISCLOSURE_DOCUMENT_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 7, isActive: true },
  { groupCode: 'ANOMALY_ALERT_STATUS', code: 'NEW', name: '신규', nameEn: 'New', sortOrder: 1, isActive: true },
  { groupCode: 'ANOMALY_ALERT_STATUS', code: 'IN_REVIEW', name: '검토중', nameEn: 'In Review', sortOrder: 2, isActive: true },
  { groupCode: 'ANOMALY_ALERT_STATUS', code: 'CONFIRMED_NORMAL', name: '정상확인', nameEn: 'Confirmed Normal', sortOrder: 3, isActive: true },
  { groupCode: 'ANOMALY_ALERT_STATUS', code: 'ACTION_TAKEN', name: '조치완료', nameEn: 'Action Taken', sortOrder: 4, isActive: true },
  { groupCode: 'ANOMALY_ALERT_STATUS', code: 'DISMISSED', name: '해제', nameEn: 'Dismissed', sortOrder: 5, isActive: true },
  { groupCode: 'ANOMALY_MODEL_STATUS', code: 'TRAINING', name: '학습중', nameEn: 'Training', sortOrder: 1, isActive: true },
  { groupCode: 'ANOMALY_MODEL_STATUS', code: 'STAGED', name: '스테이징', nameEn: 'Staged', sortOrder: 2, isActive: true },
  { groupCode: 'ANOMALY_MODEL_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 3, isActive: true },
  { groupCode: 'ANOMALY_MODEL_STATUS', code: 'SHADOW', name: '섀도우', nameEn: 'Shadow', sortOrder: 4, isActive: true },
  { groupCode: 'ANOMALY_MODEL_STATUS', code: 'RETIRED', name: '퇴역', nameEn: 'Retired', sortOrder: 5, isActive: true },
  { groupCode: 'CHATBOT_SESSION_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 1, isActive: true },
  { groupCode: 'CHATBOT_SESSION_STATUS', code: 'IDLE', name: '유휴', nameEn: 'Idle', sortOrder: 2, isActive: true },
  { groupCode: 'CHATBOT_SESSION_STATUS', code: 'EXPIRED', name: '만료', nameEn: 'Expired', sortOrder: 3, isActive: true },
  { groupCode: 'CHATBOT_SESSION_STATUS', code: 'TERMINATED', name: '종료', nameEn: 'Terminated', sortOrder: 4, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'FUTURE', name: '미개시', nameEn: 'Future', sortOrder: 1, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'OPEN', name: '열림', nameEn: 'Open', sortOrder: 2, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'TEMP_CLOSED', name: '가마감', nameEn: 'Temporary Closed', sortOrder: 3, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'CLOSED', name: '마감', nameEn: 'Closed', sortOrder: 4, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'LOCKED', name: '잠금', nameEn: 'Locked', sortOrder: 5, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'REOPEN_REQUESTED', name: '재개요청', nameEn: 'Reopen Requested', sortOrder: 6, isActive: true },
  { groupCode: 'FISCAL_PERIOD_STATUS', code: 'REOPENED', name: '재개', nameEn: 'Reopened', sortOrder: 7, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'DR', name: '차변', nameEn: 'Debit', sortOrder: 1, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'CR', name: '대변', nameEn: 'Credit', sortOrder: 2, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'RECEIPT', name: '입금', nameEn: 'Receipt', sortOrder: 3, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'PAYMENT', name: '출금', nameEn: 'Payment', sortOrder: 4, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'CLOSING_DR', name: '결산차변', nameEn: 'Closing Debit', sortOrder: 5, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'CLOSING_CR', name: '결산대변', nameEn: 'Closing Credit', sortOrder: 6, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'ACCRUAL', name: '발생주의 조정', nameEn: 'Accrual', sortOrder: 7, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'ADJUSTMENT', name: '수정', nameEn: 'Adjustment', sortOrder: 8, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'RECLASS', name: '재분류', nameEn: 'Reclass', sortOrder: 9, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'TAX_ADJ', name: '세무조정', nameEn: 'Tax Adjustment', sortOrder: 10, isActive: true },
  { groupCode: 'JOURNAL_ENTRY_CODE', code: 'STAT_ADJ', name: 'Group GAAP 조정', nameEn: 'Stat Adjustment', sortOrder: 11, isActive: true },
  { groupCode: 'NOTIFICATION_DELIVERY_STATUS', code: 'QUEUED', name: '대기열', nameEn: 'Queued', sortOrder: 1, isActive: true },
  { groupCode: 'NOTIFICATION_DELIVERY_STATUS', code: 'SENT', name: '발송', nameEn: 'Sent', sortOrder: 2, isActive: true },
  { groupCode: 'NOTIFICATION_DELIVERY_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 3, isActive: true },
  { groupCode: 'NOTIFICATION_DELIVERY_STATUS', code: 'DEAD_LETTER', name: 'DLQ', nameEn: 'Dead Letter', sortOrder: 4, isActive: true },
  { groupCode: 'NOTIFICATION_DELIVERY_STATUS', code: 'READ', name: '읽음', nameEn: 'Read', sortOrder: 5, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'UPLOADED', name: '업로드', nameEn: 'Uploaded', sortOrder: 1, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'SCANNING', name: '스캔중', nameEn: 'Scanning', sortOrder: 2, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'CLEAN', name: '정상', nameEn: 'Clean', sortOrder: 3, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'QUARANTINED', name: '격리', nameEn: 'Quarantined', sortOrder: 4, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'MATCHED', name: '매칭', nameEn: 'Matched', sortOrder: 5, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'UNMATCHED', name: '미매칭', nameEn: 'Unmatched', sortOrder: 6, isActive: true },
  { groupCode: 'EVIDENCE_STATUS', code: 'REVIEW_REQUIRED', name: '검토필요', nameEn: 'Review Required', sortOrder: 7, isActive: true },
  { groupCode: 'REPORT_PACKAGE_STATUS', code: 'PENDING', name: '대기', nameEn: 'Pending', sortOrder: 1, isActive: true },
  { groupCode: 'REPORT_PACKAGE_STATUS', code: 'GENERATED', name: '생성', nameEn: 'Generated', sortOrder: 2, isActive: true },
  { groupCode: 'REPORT_PACKAGE_STATUS', code: 'VALIDATED', name: '검증', nameEn: 'Validated', sortOrder: 3, isActive: true },
  { groupCode: 'REPORT_PACKAGE_STATUS', code: 'REVIEWED', name: '검토', nameEn: 'Reviewed', sortOrder: 4, isActive: true },
  { groupCode: 'REPORT_PACKAGE_STATUS', code: 'DELIVERED', name: '전달', nameEn: 'Delivered', sortOrder: 5, isActive: true },
  { groupCode: 'REPORT_PACKAGE_STATUS', code: 'ACKED', name: '확인', nameEn: 'Acked', sortOrder: 6, isActive: true },
  { groupCode: 'TIE_OUT_STATUS', code: 'VERIFIED', name: '검증완료', nameEn: 'Verified', sortOrder: 1, isActive: true },
  { groupCode: 'TIE_OUT_STATUS', code: 'UNVERIFIED', name: '불일치', nameEn: 'Unverified', sortOrder: 2, isActive: true },
  { groupCode: 'OPEN_ITEM_STATUS', code: 'OPEN', name: '미결', nameEn: 'Open', sortOrder: 1, isActive: true },
  { groupCode: 'OPEN_ITEM_STATUS', code: 'ANSWERED', name: '답변완료', nameEn: 'Answered', sortOrder: 2, isActive: true },
  { groupCode: 'OPEN_ITEM_STATUS', code: 'RESOLVED', name: '해소', nameEn: 'Resolved', sortOrder: 3, isActive: true },
  { groupCode: 'GROUP_REPORT_EXPORT_STATUS', code: 'DRAFT', name: '작성중', nameEn: 'Draft', sortOrder: 1, isActive: true },
  { groupCode: 'GROUP_REPORT_EXPORT_STATUS', code: 'MAPPED', name: '매핑', nameEn: 'Mapped', sortOrder: 2, isActive: true },
  { groupCode: 'GROUP_REPORT_EXPORT_STATUS', code: 'GENERATED', name: '생성', nameEn: 'Generated', sortOrder: 3, isActive: true },
  { groupCode: 'GROUP_REPORT_EXPORT_STATUS', code: 'EXPORTED', name: '내보냄', nameEn: 'Exported', sortOrder: 4, isActive: true },
  { groupCode: 'COST_CALCULATION_STATUS', code: 'OPEN', name: '열림', nameEn: 'Open', sortOrder: 1, isActive: true },
  { groupCode: 'COST_CALCULATION_STATUS', code: 'CALCULATING', name: '계산중', nameEn: 'Calculating', sortOrder: 2, isActive: true },
  { groupCode: 'COST_CALCULATION_STATUS', code: 'CALCULATED', name: '계산완료', nameEn: 'Calculated', sortOrder: 3, isActive: true },
  { groupCode: 'COST_CALCULATION_STATUS', code: 'TIED_OUT', name: '대사완료', nameEn: 'Tied Out', sortOrder: 4, isActive: true },
  { groupCode: 'COST_CALCULATION_STATUS', code: 'APPROVED', name: '승인', nameEn: 'Approved', sortOrder: 5, isActive: true },
  { groupCode: 'COST_CALCULATION_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 6, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'NOT_TARGET', name: '전송대상 아님', nameEn: 'Not Target', sortOrder: 1, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'PENDING', name: '대기', nameEn: 'Pending', sortOrder: 2, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'ISSUED', name: '발행', nameEn: 'Issued', sortOrder: 3, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'SENT', name: '전송', nameEn: 'Sent', sortOrder: 4, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'ACCEPTED', name: '접수', nameEn: 'Accepted', sortOrder: 5, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 6, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'CANCELLED', name: '취소', nameEn: 'Cancelled', sortOrder: 7, isActive: true },
  { groupCode: 'NTS_TRANSMISSION_STATUS', code: 'MANUAL_EVIDENCE', name: '수기증빙', nameEn: 'Manual Evidence', sortOrder: 8, isActive: true },
  { groupCode: 'JOURNAL_TYPE', code: 'SUBSTITUTE', name: '대체', nameEn: 'Substitute', sortOrder: 1, isActive: true },
  { groupCode: 'JOURNAL_TYPE', code: 'RECEIPT', name: '입금', nameEn: 'Receipt', sortOrder: 2, isActive: true },
  { groupCode: 'JOURNAL_TYPE', code: 'PAYMENT', name: '출금', nameEn: 'Payment', sortOrder: 3, isActive: true },
  { groupCode: 'JOURNAL_TYPE', code: 'PURCHASE', name: '매입', nameEn: 'Purchase', sortOrder: 4, isActive: true },
  { groupCode: 'JOURNAL_TYPE', code: 'SALES', name: '매출', nameEn: 'Sales', sortOrder: 5, isActive: true },
  { groupCode: 'JOURNAL_NUMBERING_STATUS', code: 'PLANNED', name: '예정', nameEn: 'Planned', sortOrder: 1, isActive: true },
  { groupCode: 'JOURNAL_NUMBERING_STATUS', code: 'CONFIRMED', name: '확정', nameEn: 'Confirmed', sortOrder: 2, isActive: true },
  { groupCode: 'JOURNAL_NUMBERING_STATUS', code: 'NUMBERING_CONFLICT', name: '채번충돌', nameEn: 'Numbering Conflict', sortOrder: 3, isActive: true },
  { groupCode: 'BUSINESS_PARTNER_STATUS', code: 'TEMP_VENDOR', name: '임시 공급업체', nameEn: 'Temporary Vendor', sortOrder: 1, isActive: true },
  { groupCode: 'BUSINESS_PARTNER_STATUS', code: 'TEMP_CUSTOMER', name: '임시 고객', nameEn: 'Temporary Customer', sortOrder: 2, isActive: true },
  { groupCode: 'BUSINESS_PARTNER_STATUS', code: 'PENDING_APPROVAL', name: '승인대기', nameEn: 'Pending Approval', sortOrder: 3, isActive: true },
  { groupCode: 'BUSINESS_PARTNER_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 4, isActive: true },
  { groupCode: 'BUSINESS_PARTNER_STATUS', code: 'INACTIVE', name: '사용중지', nameEn: 'Inactive', sortOrder: 5, isActive: true },
  { groupCode: 'BUSINESS_PARTNER_STATUS', code: 'CLOSED_BIZ', name: '휴폐업', nameEn: 'Closed Business', sortOrder: 6, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'DRAFT', name: '작성중', nameEn: 'Draft', sortOrder: 1, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'CLIENT_SUBMITTED', name: '고객제출', nameEn: 'Client Submitted', sortOrder: 2, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'REVIEWING', name: '검토중', nameEn: 'Reviewing', sortOrder: 3, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'PENDING_APPROVAL', name: '승인대기', nameEn: 'Pending Approval', sortOrder: 4, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 5, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'APPROVED', name: '승인', nameEn: 'Approved', sortOrder: 6, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'POSTED', name: '기표', nameEn: 'Posted', sortOrder: 7, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'ADJUSTED', name: '조정', nameEn: 'Adjusted', sortOrder: 8, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'REVERSED', name: '역분개', nameEn: 'Reversed', sortOrder: 9, isActive: true },
  { groupCode: 'JOURNAL_STATUS', code: 'CANCELLED', name: '취소', nameEn: 'Cancelled', sortOrder: 10, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'DRAFT', name: '작성중', nameEn: 'Draft', sortOrder: 1, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'IN_PROGRESS', name: '진행중', nameEn: 'In Progress', sortOrder: 2, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'APPROVED', name: '승인', nameEn: 'Approved', sortOrder: 3, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 4, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'WITHDRAWN', name: '회수', nameEn: 'Withdrawn', sortOrder: 5, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'FINALIZED', name: '종결', nameEn: 'Finalized', sortOrder: 6, isActive: true },
  { groupCode: 'APPROVAL_STATUS', code: 'POST_PENDING', name: '기표대기', nameEn: 'Post Pending', sortOrder: 7, isActive: true },
  { groupCode: 'SERVICE_CONTRACT_STATUS', code: 'PENDING', name: '대기', nameEn: 'Pending', sortOrder: 1, isActive: true },
  { groupCode: 'SERVICE_CONTRACT_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 2, isActive: true },
  { groupCode: 'SERVICE_CONTRACT_STATUS', code: 'SUSPENDED', name: '정지', nameEn: 'Suspended', sortOrder: 3, isActive: true },
  { groupCode: 'SERVICE_CONTRACT_STATUS', code: 'TERMINATED', name: '종료', nameEn: 'Terminated', sortOrder: 4, isActive: true },
  { groupCode: 'SERVICE_CONTRACT_STATUS', code: 'EXPIRED', name: '만료', nameEn: 'Expired', sortOrder: 5, isActive: true },
  { groupCode: 'ASSIGNMENT_STATUS', code: 'ASSIGNED', name: '배정', nameEn: 'Assigned', sortOrder: 1, isActive: true },
  { groupCode: 'ASSIGNMENT_STATUS', code: 'TRANSFER_REQUESTED', name: '이관요청', nameEn: 'Transfer Requested', sortOrder: 2, isActive: true },
  { groupCode: 'ASSIGNMENT_STATUS', code: 'TRANSFERRED', name: '이관완료', nameEn: 'Transferred', sortOrder: 3, isActive: true },
  { groupCode: 'ASSIGNMENT_STATUS', code: 'ENDED', name: '종료', nameEn: 'Ended', sortOrder: 4, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'REQUESTED', name: '요청', nameEn: 'Requested', sortOrder: 1, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'UPLOADED', name: '업로드', nameEn: 'Uploaded', sortOrder: 2, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'IN_PROGRESS', name: '진행중', nameEn: 'In Progress', sortOrder: 3, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'REVIEWING', name: '검토중', nameEn: 'Reviewing', sortOrder: 4, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'CLIENT_CONFIRMING', name: '고객확인', nameEn: 'Client Confirming', sortOrder: 5, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'COMPLETED', name: '완료', nameEn: 'Completed', sortOrder: 6, isActive: true },
  { groupCode: 'CLIENT_TASK_STATUS', code: 'ON_HOLD', name: '보류', nameEn: 'On Hold', sortOrder: 7, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'DRAFT', name: '작성중', nameEn: 'Draft', sortOrder: 1, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'READY_TO_SEND', name: '전송준비', nameEn: 'Ready To Send', sortOrder: 2, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'SENT', name: '전송', nameEn: 'Sent', sortOrder: 3, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'ACCEPTED', name: '접수', nameEn: 'Accepted', sortOrder: 4, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'FAILED', name: '실패', nameEn: 'Failed', sortOrder: 5, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'CANCELLED', name: '취소', nameEn: 'Cancelled', sortOrder: 6, isActive: true },
  { groupCode: 'TAX_INVOICE_STATUS', code: 'RETRY_PENDING', name: '재시도대기', nameEn: 'Retry Pending', sortOrder: 7, isActive: true },
  { groupCode: 'FILING_FILE_STATUS', code: 'CREATED', name: '생성', nameEn: 'Created', sortOrder: 1, isActive: true },
  { groupCode: 'FILING_FILE_STATUS', code: 'VALIDATED', name: '검증', nameEn: 'Validated', sortOrder: 2, isActive: true },
  { groupCode: 'FILING_FILE_STATUS', code: 'SUBMITTED', name: '제출', nameEn: 'Submitted', sortOrder: 3, isActive: true },
  { groupCode: 'FILING_FILE_STATUS', code: 'ACCEPTED', name: '접수', nameEn: 'Accepted', sortOrder: 4, isActive: true },
  { groupCode: 'FILING_FILE_STATUS', code: 'REJECTED', name: '반려', nameEn: 'Rejected', sortOrder: 5, isActive: true },
  { groupCode: 'ASSET_STATUS', code: 'REGISTERED', name: '등록', nameEn: 'Registered', sortOrder: 1, isActive: true },
  { groupCode: 'ASSET_STATUS', code: 'ACTIVE', name: '활성', nameEn: 'Active', sortOrder: 2, isActive: true },
  { groupCode: 'ASSET_STATUS', code: 'TRANSFERRED', name: '이동', nameEn: 'Transferred', sortOrder: 3, isActive: true },
  { groupCode: 'ASSET_STATUS', code: 'DISPOSED', name: '처분', nameEn: 'Disposed', sortOrder: 4, isActive: true },
  { groupCode: 'ASSET_STATUS', code: 'CLOSED', name: '종료', nameEn: 'Closed', sortOrder: 5, isActive: true },
  { groupCode: 'VAT_RETURN_TYPE', code: 'PRELIMINARY', name: '예정', nameEn: 'Preliminary', sortOrder: 1, isActive: true },
  { groupCode: 'VAT_RETURN_TYPE', code: 'FINAL', name: '확정', nameEn: 'Final', sortOrder: 2, isActive: true },
  { groupCode: 'VAT_RETURN_TYPE', code: 'AMENDED', name: '수정', nameEn: 'Amended', sortOrder: 3, isActive: true },
  { groupCode: 'VAT_RETURN_TYPE', code: 'LATE', name: '기한후', nameEn: 'Late', sortOrder: 4, isActive: true },
  { groupCode: 'BOOKKEEPING_SCOPE_TYPE', code: 'JOURNAL_TYPE', name: '전표유형', nameEn: 'Journal Type', sortOrder: 1, isActive: true },
  { groupCode: 'BOOKKEEPING_SCOPE_TYPE', code: 'TRANSACTION_SOURCE', name: '거래원천', nameEn: 'Transaction Source', sortOrder: 2, isActive: true },
  { groupCode: 'BOOKKEEPING_SCOPE_TYPE', code: 'ACCOUNT_RANGE', name: '계정범위', nameEn: 'Account Range', sortOrder: 3, isActive: true },
  { groupCode: 'BOOKKEEPING_SCOPE_TYPE', code: 'MODULE', name: '모듈', nameEn: 'Module', sortOrder: 4, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_ACCOUNT', name: '표준계정 템플릿', nameEn: 'Standard Account', sortOrder: 1, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_VAT', name: '부가세 세율/과세유형', nameEn: 'Standard VAT', sortOrder: 2, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_TAX_RULE', name: '세법 룰 마스터', nameEn: 'Standard Tax Rule', sortOrder: 3, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_WITHHOLDING', name: '원천세 기준', nameEn: 'Standard Withholding', sortOrder: 4, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_FORM', name: '신고서식', nameEn: 'Standard Form', sortOrder: 5, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_CODE', name: '공통코드', nameEn: 'Standard Code', sortOrder: 6, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_ROLE', name: 'Role 템플릿', nameEn: 'Standard Role', sortOrder: 7, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_APPROVAL', name: '결재선 템플릿', nameEn: 'Standard Approval', sortOrder: 8, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_CASHFLOW', name: '현금흐름 매핑', nameEn: 'Standard Cashflow', sortOrder: 9, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_TAXONOMY', name: 'XBRL 분류체계', nameEn: 'Standard Taxonomy', sortOrder: 10, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_CONVERSION', name: '기준 변환규칙', nameEn: 'Standard Conversion', sortOrder: 11, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_ANOMALY_RULE', name: '이상탐지 규칙', nameEn: 'Standard Anomaly Rule', sortOrder: 12, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_NOTIFICATION', name: '알림 템플릿', nameEn: 'Standard Notification', sortOrder: 13, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_REPORT_PACKAGE', name: '보고패키지 템플릿', nameEn: 'Standard Report Package', sortOrder: 14, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_SCHEDULE', name: '명세서 템플릿', nameEn: 'Standard Schedule', sortOrder: 15, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_GROUP_MAPPING', name: '그룹 보고 매핑', nameEn: 'Standard Group Mapping', sortOrder: 16, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_ACCOUNT_L10N', name: '다국어 계정명', nameEn: 'Standard Account Localization', sortOrder: 17, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_COSTING', name: '제조원가 템플릿', nameEn: 'Standard Costing', sortOrder: 18, isActive: true },
  { groupCode: 'STANDARD_CATALOG_CODE', code: 'STD_PURCHASE_TAX_STATUS', name: '매입원장 세무상태', nameEn: 'Standard Purchase Tax Status', sortOrder: 19, isActive: true },
  { groupCode: 'DIMENSION_TYPE', code: 'BUSINESS_PLACE', name: '사업장', nameEn: 'Business Place', sortOrder: 1, isActive: true },
  { groupCode: 'DIMENSION_TYPE', code: 'COST_CENTER', name: '코스트센터', nameEn: 'Cost Center', sortOrder: 2, isActive: true },
  { groupCode: 'DIMENSION_TYPE', code: 'DEPARTMENT', name: '부서', nameEn: 'Department', sortOrder: 3, isActive: true },
  { groupCode: 'DIMENSION_TYPE', code: 'PROJECT', name: '프로젝트', nameEn: 'Project', sortOrder: 4, isActive: true },
  { groupCode: 'DIMENSION_TYPE', code: 'SITE', name: '현장', nameEn: 'Site', sortOrder: 5, isActive: true },
  { groupCode: 'DIMENSION_TYPE', code: 'EMPLOYEE', name: '사원', nameEn: 'Employee', sortOrder: 6, isActive: true },
  { groupCode: 'JOURNAL_APPROVAL_MODE', code: 'REQUIRED', name: '필수', nameEn: 'Required', sortOrder: 1, isActive: true },
  { groupCode: 'JOURNAL_APPROVAL_MODE', code: 'OPTIONAL', name: '선택', nameEn: 'Optional', sortOrder: 2, isActive: true },
  { groupCode: 'JOURNAL_APPROVAL_MODE', code: 'NONE', name: '없음', nameEn: 'None', sortOrder: 3, isActive: true },
  { groupCode: 'CASH_FLOW_ACTIVITY', code: 'OPERATING', name: '영업활동', nameEn: 'Operating', sortOrder: 1, isActive: true },
  { groupCode: 'CASH_FLOW_ACTIVITY', code: 'INVESTING', name: '투자활동', nameEn: 'Investing', sortOrder: 2, isActive: true },
  { groupCode: 'CASH_FLOW_ACTIVITY', code: 'FINANCING', name: '재무활동', nameEn: 'Financing', sortOrder: 3, isActive: true },
  { groupCode: 'DISCLOSURE_REPORT_TYPE', code: 'ANNUAL', name: '사업보고서', nameEn: 'Annual', sortOrder: 1, isActive: true },
  { groupCode: 'DISCLOSURE_REPORT_TYPE', code: 'SEMI', name: '반기보고서', nameEn: 'Semiannual', sortOrder: 2, isActive: true },
  { groupCode: 'DISCLOSURE_REPORT_TYPE', code: 'QUARTER', name: '분기보고서', nameEn: 'Quarterly', sortOrder: 3, isActive: true },
  { groupCode: 'DISCLOSURE_REPORT_TYPE', code: 'AUDIT', name: '감사보고서 첨부', nameEn: 'Audit', sortOrder: 4, isActive: true },
  { groupCode: 'DISCLOSURE_REPORT_TYPE', code: 'SUBMISSION', name: '제출용', nameEn: 'Submission', sortOrder: 5, isActive: true },
  { groupCode: 'ACCOUNTING_STANDARD', code: 'K_GAAP', name: '일반기업회계기준', nameEn: 'K-GAAP', sortOrder: 1, isActive: true },
  { groupCode: 'ACCOUNTING_STANDARD', code: 'K_IFRS', name: '한국채택국제회계기준', nameEn: 'K-IFRS', sortOrder: 2, isActive: true },
  { groupCode: 'ACCOUNTING_STANDARD', code: 'US_GAAP', name: '미국회계기준', nameEn: 'US GAAP', sortOrder: 3, isActive: true },
  { groupCode: 'ACCOUNTING_STANDARD', code: 'IFRS', name: '국제회계기준', nameEn: 'IFRS', sortOrder: 4, isActive: true },
  { groupCode: 'ACCOUNTING_STANDARD', code: 'JP_GAAP', name: '일본회계기준', nameEn: 'JP GAAP', sortOrder: 5, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'VENDOR', name: '거래처', nameEn: 'Vendor', sortOrder: 1, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'NOTE', name: '어음', nameEn: 'Note', sortOrder: 2, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'BANK', name: '은행', nameEn: 'Bank', sortOrder: 3, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'CARD', name: '카드', nameEn: 'Card', sortOrder: 4, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'ADVANCE', name: '가지급금', nameEn: 'Advance', sortOrder: 5, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'VAT', name: '부가세', nameEn: 'VAT', sortOrder: 6, isActive: true },
  { groupCode: 'AUX_LEDGER_TYPE', code: 'QTY', name: '수량', nameEn: 'Quantity', sortOrder: 7, isActive: true },
  { groupCode: 'TENANT_INPUT_POLICY', code: 'NONE', name: '입력 차단', nameEn: 'None', sortOrder: 1, isActive: true },
  { groupCode: 'TENANT_INPUT_POLICY', code: 'REQUEST_ONLY', name: '기장 요청만 허용', nameEn: 'Request Only', sortOrder: 2, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'HELD', name: '보관', nameEn: 'Held', sortOrder: 1, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'DISCOUNTED', name: '할인', nameEn: 'Discounted', sortOrder: 2, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'ENDORSED', name: '배서', nameEn: 'Endorsed', sortOrder: 3, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'MATURED', name: '만기', nameEn: 'Matured', sortOrder: 4, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'DEFAULTED', name: '부도', nameEn: 'Defaulted', sortOrder: 5, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'PARTIAL_DISCOUNTED', name: '부분할인', nameEn: 'Partial Discounted', sortOrder: 6, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'RETURNED', name: '반환', nameEn: 'Returned', sortOrder: 7, isActive: true },
  { groupCode: 'BILL_RECEIVABLE_STATUS', code: 'SPLIT_ENDORSED', name: '분할배서', nameEn: 'Split Endorsed', sortOrder: 8, isActive: true },
  { groupCode: 'BILL_PAPER_STATUS', code: 'UNISSUED', name: '미발행', nameEn: 'Unissued', sortOrder: 1, isActive: true },
  { groupCode: 'BILL_PAPER_STATUS', code: 'ISSUED', name: '발행', nameEn: 'Issued', sortOrder: 2, isActive: true },
  { groupCode: 'BILL_PAPER_STATUS', code: 'SETTLED', name: '결제', nameEn: 'Settled', sortOrder: 3, isActive: true },
  { groupCode: 'BILL_PAPER_STATUS', code: 'COLLATERALIZED', name: '담보', nameEn: 'Collateralized', sortOrder: 4, isActive: true },
  { groupCode: 'BILL_PAPER_STATUS', code: 'DISCARDED', name: '폐기', nameEn: 'Discarded', sortOrder: 5, isActive: true },
];
