/**
 * 표준 오류 코드 (설계서 CO-04 검증·오류 처리 준거)
 * API 오류 응답의 error.code 로 사용한다.
 */
export const ErrorCodes = {
  // 인증/인가
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCESS_DENIED: 'ACCESS_DENIED',
  STEPUP_REQUIRED: 'STEPUP_REQUIRED',

  // 요청/검증
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // 도메인 (설계서 표준 코드)
  NUMBERING_CONFLICT: 'NUMBERING_CONFLICT',
  POSTED_IMMUTABLE: 'POSTED_IMMUTABLE',
  CLOSING_LOCKED: 'CLOSING_LOCKED',
  SOD_VIOLATION: 'SOD_VIOLATION',
  DIMENSION_REQUIRED: 'DIMENSION_REQUIRED',
  AUX_REQUIRED: 'AUX_REQUIRED',

  // 개인정보/보안
  PRIVACY_REASON_REQUIRED: 'PRIVACY_REASON_REQUIRED',
  BULK_ACTION_THRESHOLD: 'BULK_ACTION_THRESHOLD',

  // 시스템
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
